### ISSUE TITLE
[ERROR:0] global /io/opencv/modules/videoio/src/cap.cpp (116) open VIDEOIO(CV_IMAGES): raised OpenCV exception:  OpenCV(4.2.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): ./input_stream.avi in function 'icvExtractPattern'   Error: Opening video stream or file ./input_stream.avi

### ISSUE THREAD

**Issue by testchange** [IIT-PAVIS/Social-Distancing#6]
When I run the below command:

```
python3 social-distancing.py --image_in ./samples/286.jpg --image_out output.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7 
```

I run into this issue below which is weird because I am testing an image not video...

```
[ERROR:0] global /io/opencv/modules/videoio/src/cap.cpp (116) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.2.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): ./input_stream.avi in function 'icvExtractPattern'


Error: Opening video stream or file ./input_stream.avi
```

**Comment by pmorerio** [comment]
Have you tried adding `--image enabled` to the command string?

**Comment by testchange** [comment]
Yes I did run:

```
python3 social-distancing.py --image enabled  --img_inp ./samples/286.jpg --img_out output.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7
```

but I received this error message.

```
Error: unable to use video and image mode at the same time!
```
I appreciate your help as your codebase will help my local community to observe social distancing.

**Comment by pmorerio** [comment]
Ok, since video is enabled by default I guess you should combine `--image enabled --video disabled`

**Comment by testchange** [comment]
Here is the code I run:
```
python3 social-distancing.py --image enabled --video disabled --image_in ./samples/286.jpg --image_out output.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7
```

Here's the error

```
Starting OpenPose Python Wrapper...

Error:
Prototxt file not found: /home/dexmac/openpose/models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():58
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():94
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():106
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():102
- /openpose/src/openpose/pose/poseExtractor.cpp:initializationOnThread():34
- /openpose/include/openpose/pose/wPoseExtractor.hpp:initializationOnThread():57
- /openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77
Traceback (most recent call last):
  File "social-distancing.py", line 715, in <module>
    social_distance = SocialDistancing(args)
  File "social-distancing.py", line 254, in __init__
    self.jpeg = TurboJPEG()
  File "/usr/local/lib/python3.6/dist-packages/turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "/usr/local/lib/python3.6/dist-packages/turbojpeg.py", line 424, in __find_turbojpeg
    'Unable to locate turbojpeg library automatically. '
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Prototxt file not found: /home/dexmac/openpose/models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():58
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():94
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():106
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():102
- /openpose/src/openpose/pose/poseExtractor.cpp:initializationOnThread():34
- /openpose/include/openpose/pose/wPoseExtractor.hpp:initializationOnThread():57
- /openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77
- [All threads closed and control returned to main thread]
- /openpose/src/openpose/utilities/errorAndLog.cpp:checkWorkerErrors():280
- /openpose/include/openpose/thread/threadManager.hpp:stop():243
- /openpose/include/openpose/wrapper/wrapper.hpp:stop():455
- /openpose/include/openpose/wrapper/wrapper.hpp:~WrapperT():282
- [Error occurred in a destructor or in the OpenPose Unity Plugin, so no std::exception has been thrown. Returning with exit status 0]
```

**Comment by pmorerio** [comment]
As suggested, this error can happen for three reasons. Have you installed openpose? You should provide the path via the `--openpose_folder` argument.

**Comment by testchange** [comment]
So I manage to solve partially with your `--openpose_folder` running:
```
python3 social-distancing.py --image enabled --video disabled --image_in ./samples/286.jpg --image_out output.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7 --openpose_folder ../openpose/models/
```

Here's the new error :/ Just for context, I install `turbojpeg` in Ubuntu via 
```pip3 install PyTurboJPEG```
```
Starting OpenPose Python Wrapper...
Traceback (most recent call last):
  File "social-distancing.py", line 715, in <module>
    social_distance = SocialDistancing(args)
  File "social-distancing.py", line 254, in __init__
    self.jpeg = TurboJPEG()
  File "/usr/local/lib/python3.6/dist-packages/turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "/usr/local/lib/python3.6/dist-packages/turbojpeg.py", line 424, in __find_turbojpeg
    'Unable to locate turbojpeg library automatically. '
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
```

When I add the path to the `lib_path` it returns this error:
```
Starting OpenPose Python Wrapper...
Traceback (most recent call last):
  File "social-distancing.py", line 715, in <module>
    social_distance = SocialDistancing(args)
  File "social-distancing.py", line 254, in __init__
    self.jpeg = TurboJPEG("/usr/local/lib/python3.6/dist-packages/turbojpeg.py")
  File "/usr/local/lib/python3.6/dist-packages/turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/turbojpeg.py: invalid ELF header
```

**Additional Info:**
I install `openpose` using this Docker image https://github.com/esemeniuc/openpose-docker/blob/master/Dockerfile

I have tried importing `openpose` using interactive python3 and it works so I can rule out that the `openpose` library is the issue.

**Steps I have taken before encountering this issue:**
(1) I am running on AWS EC2 platform using Ubuntu 18.04(https://aws.amazon.com/releasenotes/aws-deep-learning-ami-ubuntu-18-04-version-28-1/)
(2) I built and ran the `openpose` image (https://github.com/esemeniuc/openpose-docker/blob/master/Dockerfile)
(3) I git cloned your repo and changed the `sys` directory to `../openpose/build/python` in `social_distancing.py` to retrieve the `openpose` library(before this step I keep running into missing `openpose` module error)
(4) I ran the below code to install `turbojpeg` library
```
apt install python3-pip
pip3 install setup tools
pip3 install PyTurboJPEG
``` 
(6) Finally, I ran 
```
python3 social-distancing.py --image enabled --video disabled --image_in ./samples/286.jpg --image_out output.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7 --openpose_folder ../openpose/models/
```
to get the above error message.

**Comment by mayaghaei** [comment]
it seems the path you give to `turbojpeg` is not a valid shared library. do you possibly have different versions of python and you installed `turbojpeg` on another version that you are not using for running this code?

**Comment by testchange** [comment]
yep I have 2 python at least when I typed `which python` and `which python3`. The results are:
```
/usr/bin/python
/usr/bin/python3
```

Hmm, since I `pip3 install PyTurboJPEG` and I run `python3 ...` it should retrieve the library from `/usr/local/lib/python3.6/dist-packages` isn't it? Pardon me if I am wrong. Also, I have this directory `/usr/local/lib/python3.6/dist-packages/turbojpeg.py`. So I dont understand why I am still facing this issue.

**Comment by mayaghaei** [comment]
I recommend uninstallig ‘turbojpeg’ from both python 2 and 3, and try to install it again only with ‘pip3’. in your previous comment before editting I could see you first tried to install it with ‘pip’ only, thus python2

**Comment by testchange** [comment]
Nope I did not install with `pip` because when I type `pip uninstall` it shows `bash: pip: command not found`. Nevertheless, I `pip3 uninstall PyTurboJPEG` and `pip3 install PyTurboJPEG` but to no avail :/

Full error message:

```
Starting OpenPose Python Wrapper...
Traceback (most recent call last):
  File "social-distancing.py", line 715, in <module>
    social_distance = SocialDistancing(args)
  File "social-distancing.py", line 254, in __init__
    self.jpeg = TurboJPEG()
  File "/usr/local/lib/python3.6/dist-packages/turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "/usr/local/lib/python3.6/dist-packages/turbojpeg.py", line 424, in __find_turbojpeg
    'Unable to locate turbojpeg library automatically. '
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
```

**Comment by mayaghaei** [comment]
would you please again uninstall pyTurboJPEG and follow the instruction given in this like to install it? I think you are using Linux right? please follow those instructions.
https://pypi.org/project/PyTurboJPEG/

**Comment by testchange** [comment]
Thanks have resolved the issue will release a working Dockerfile and share with you guys so more people can benefit from this.

**Comment by mayaghaei** [comment]
cool! happy to hear that! and thanks for your contribution :)
